config/routes.rb
Rails.application.routes.draw do


  resources :rejections
  resources :campnotes
  resources :recuploads
  resources :feedbacks
  # resources :payments
  root to: 'static_pages#index'

  devise_for :admins, ActiveAdmin::Devise.config
  get '/admin/reports/all_complete_apps', to: 'admin/reports#all_complete_apps', as: :admin_reports_all_complete_apps
  get '/admin/reports/registered_but_not_applied', to: 'admin/reports#registered_but_not_applied', as: :admin_reports_registered_but_not_applied
  get '/admin/reports/enrolled_with_addresses', to: 'admin/reports#enrolled_with_addresses', as: :admin_reports_enrolled_with_addresses
  get '/admin/reports/course_assignments_with_students', to: 'admin/reports#course_assignments_with_students', as: :admin_reports_course_assignments_with_students

  ActiveAdmin.routes(self)
  # authenticated :admin do
    resources :genders
    resources :demographics

    resources :camp_configurations do
      resources :camp_occurrences
    end

    resources :camp_occurrences do
      resources :activities
    end

    resources :camp_occurrences do
      resources :courses
    end

    resources :activities
    resources :courses
  # end

  devise_for :users
  resources :applicant_details

  resources :enrollments do
    resources :travels
  end

  resources :enrollments do
    resources :activities
  end

  resources :enrollments do
      resources :financial_aids
  end

  resources :financial_aids

  resources :enrollments do
    resources :recommendations
  end

  resources :recommendations

  resources :enrollments do
    resources :course_preferences
  end

  resources :enrollments do
    resources :course_assignments
  end

  resources :enrollments do
    resources :session_assignments
  end

  resources :course_preferences
  resources :course_assignments
  resources :session_assignments
  
  # post 'accept_offer', to: 'enrollments#accept_offer'
  # post 'decline_offer', to: 'enrollments#decline_offer'

  post 'accept_session_offer/:id', to: 'session_assignments#accept_session_offer', as: :accept_session_offer
  post 'decline_session_offer/:id', to: 'session_assignments#decline_session_offer', as: :decline_session_offer

  post 'waitlisted/:id', to: 'enrollments#add_to_waitlist', as: :waitlisted

  get 'static_pages/index'
  get 'static_pages/contact'
  get 'static_pages/privacy'


  get 'payments', to: 'payments#index'
  get 'payment_receipt', to: 'payments#payment_receipt'
  post 'payment_receipt', to: 'payments#payment_receipt'
  get 'payment_show', to: 'payments#payment_show', as: 'all_payments'
  get 'make_payment', to: 'payments#make_payment'
  post 'make_payment', to: 'payments#make_payment'

  get 'recupload_error', to: 'recuploads#error'
  get 'recupload_success', to: 'recuploads#success'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get 'send_request_email', to: 'recommendations#send_request_email', as: :send_request_email

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include ApplicantState
  # devise_group :logged_in, contains: [:user, :admin]
  # before_action :authenticate_logged_in!, except: [:contact :privacy]
  # before_action :authenticate_admin!, only: [:destroy]
  before_action :set_current_enrollment

  def index
    @application_materials_due_date = CampConfiguration.active_camp_materials_due_date
    @active_camp_exists = CampConfiguration.active.exists?
    @current_camp_year = CampConfiguration.active_camp_year
  end

  def contact
  end

  def privacy
  end

  private
    def set_current_enrollment
      if user_signed_in?
        @current_enrollment = current_user.enrollments.current_camp_year_applications.last
      end
    end
end

app/views/static_pages/_directions.html.erb
<% if user_signed_in? %>
  <% if current_user.applicant_detail.blank? %>
    <div class="m-2">
        <%= link_to 'Registration', new_applicant_detail_path,
                    class: 'btn btn-blue' %>
      <p class ="mt-2">
        As you advance through the application process, these directions will be updated. 
        For many items you submit, you will receive an event update on the right side of the screen.
      </p>
    </div>
    <p class='direction_notes'>
      Watch here for special information related to the step you currently
      are on.
    </p>
  <% elsif @current_enrollment.nil? %>
    <div class="m-2">
      <%= link_to 'Camp Application', new_enrollment_path,
                  class: 'btn btn-blue' %>
      
      <p class ="mt-2">The next step is to submit your application.</p>
      <p>Check your work before submitting. Once review of your application begins, you will not be able to make changes.</p>
    </div>
      <p class='direction_notes'>Make sure that you have gathered all the
        required information, then work your way through the sections.
      </p>
     
      <div class='direction_notes'>
        <ul class="dirdot">
          <li class="dirdot">High School Address</li>
          <li class="dirdot">Transcript (in pdf, png, or jpg format)</li>
          <li class="dirdot">Your personal statement</li>
        </ul>
      </div>
        <p class='direction_notes'>
          You will be selecting the activities and courses you wish to participate in. 
          After this stage is complete, your next step will be to rank the courses 
          related to your interest.
        </p>
        
  <% elsif @current_enrollment.course_preferences.pluck(:ranking).any?{ |e| e.nil? } %>
    <div class="m-2">
      <%= link_to 'Course-Rankings',
                        enrollment_course_preferences_path(@current_enrollment.id),
                        class: 'btn btn-blue' %>
        <p class="mt-2">
          The next step is to rank the courses you selected in priority of interest. You should give a 
          rank of "1" for the first or highest preferred course.
        </p>
    </div>
    <div class='m-2 direction_notes'>Make sure that you give each course you selected a ranking. </div>   
  <% elsif @current_enrollment.recommendation.blank? %>
    <div class="m-2">
      <%= link_to "Request Letter of Recommendation",
                  new_enrollment_recommendation_path(@current_enrollment),
                  class: 'btn btn-blue'  %>
        <p class="mt-2">Please ask one of your most recent high school science or math
      teachers to submit a Letter of Recommendation. </p>
    </div>
    <div class='direction_notes'>
      This is a required part
      of your application. Your recommender will be sent an email giving
      them directions on how to submit a recommendation for you, so please
      be certain that you enter their correct email address.
    </div>
  <% elsif current_user.payments.current_camp_payments.empty? %>
    <div class="m-2">Now that you've submitted your application, the next step is to make
      sure you pay the <%= humanized_money_with_symbol(current_camp_fee / 100) %> non-refundable application fee
      <%= button_to "pay #{humanized_money_with_symbol(current_camp_fee / 100)} application fee",
                  make_payment_path(amount: current_camp_fee / 100), class: 'bg-blue-700 hover:bg-blue-900 text-gray-100 font-normal py-1 px-2 rounded' %>
    </div>
    <p class="text-red-700 m-2">
      Payment of your application fee must be completed before you will be
      considered for admission.
    </p>
    <p class="direction_notes">
      International students may pay via wire transfer
      (<a href="mailto:mmss@umich.edu">contact our office</a> for more
      information regarding wire transfers for international students.)
    </p>
    <p class="direction_notes">You will receive an email from UM
      MerchantServices confirming your credit card transactions.
    </p>
  <% else %>
    <% if @current_enrollment.application_status == "waitlisted" %>
      <div class="m-2">
        <p class="direction_notes">
          Your application was placed onto the wait list.</p>
      </div>
    <% elsif @current_enrollment.application_status == "rejected" %>
      <div class="m-2">
        <p class="direction_notes">
          Your application was rejected.</p>
      </div>
    <% elsif @current_enrollment.offer_status == "offered" %>
      <div class="m-2">
        <p class="direction_notes">
          Please respond to our acceptance offer by making the appropriate
          selection in the Progress Window.</p>
      </div>
    <% elsif @current_enrollment.application_status == "offer accepted" %>
      <div class="m-2">
        <% unless current_enrollment.student_packet.attached? %>
          <p>You need to download, fill out and upload the Student Information Packet using
          the button in the progress window to the right.</p>
        <% end %>
        <p>Please refer to your offer email for the payment deadline. To 
        check your account balance click the button below.</p>
        <div class="my-2">
          <%= link_to "Account Summary", all_payments_path, class: "btn btn-blue pt-8"%>
        </div>
      </div>
    <% elsif @current_enrollment.application_status == "offer declined" %>
      <div class="m-2">
        <p class="direction_notes">
          Thanks for your interest.
        </p>
      </div>
    <% elsif @current_enrollment.application_status == "enrolled" %>
      <div class="m-2">
        <p class="direction_notes">
          We look forward to seeing you at the <%= @current_camp_year %> University of Michigan MMSS High School Summer Program.
        </p>
      </div>
    <% else %>
      <div class="m-2">
        <p class="direction_notes">
          At this point, you have submitted all of the information needed from
          YOU. 
          <% if @current_enrollment.recommendation.recupload.blank? %>
            However, <strong>please note that your application will not be
            considered "complete", and will not be reviewed until we receive the
            letter of recommendation from your teacher. Please check with your
            teacher to make sure they know you have applied, and they have
            received an email from us!</strong>
          <% end %>
        </p>
      </div>
    <% end %>

    <% if @current_enrollment.financial_aids.blank? &&
    (@current_enrollment.application_status == nil || @current_enrollment.application_status == "" ||
    @current_enrollment.application_status == "submitted" || @current_enrollment.application_status == "application complete") %>
        <div class="m-2">
          <p class="mb-2">If you are applying for need-based financial support, please fill out a request.</p>
          <%= link_to "Financial Aid Request", new_enrollment_financial_aid_path(@current_enrollment),
                class: "btn btn-blue" %>
        </div>
    <% end %>

    <p class="direction_notes"> Watch the progress window at the right
      to track the status of your application materials. You will receive an
      email with instructions for any additional steps that are required.
    </p>
  <% end %>

<% else %>
  <% if @active_camp_exists %>
    <% if registration_open %>
      <div class="mt-2">
        <%= link_to 'Sign up', new_user_registration_path,
                  class: "btn btn-blue"  %>
        <%= link_to 'Returning User - Sign In', new_user_session_path,
                    class: "btn btn-blue" %>
      </div>
    <% elsif new_registration_closed %>
      <div class="mt-2">
        <p class='direction_notes mb-2' >We have closed the registration for new applications.</p>
        <%= link_to 'Returning User - Sign In', new_user_session_path,
                  class: "btn btn-blue" %>
      </div>
    <% else %>
      <div class='direction_notes mt-2' >
        MMSS Student Portal will be open for registration <%= current_camp_year_app_opens.strftime("%B %d, %Y") %>.
      </div>
    <% end %>
  <% else %>
    <div class="mt-2">
        <p class='direction_notes mb-2' >There are currently no active camps.</p>
    </div>
  <% end %>
<% end %>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/index.html.erb
<h1 class="text-yellow-um_yellow bg-blue-um_blue p-2">Michigan Math and Science Scholars Registration</h1>
<% unless user_signed_in? %>
<div class= "my-4">
  <p>
    Welcome to the Michigan Math and Science Scholars (MMSS) WebApply. MMSS is a program
    designed to introduce high school students to current developments and
    research in the sciences and to encourage the next generation of researchers
    to develop and retain a love of mathematics and science.
  </p>
</div>
<% end %>
<%= render 'directions' %>

app/views/static_pages/privacy.html.erb
<h1>StaticPages#privacy</h1>
<p>Find me in app/views/static_pages/privacy.html.erb</p>