config/routes.rb
Rails.application.routes.draw do


  resources :rejections
  resources :campnotes
  resources :recuploads
  resources :feedbacks
  # resources :payments
  root to: 'static_pages#index'

  devise_for :admins, ActiveAdmin::Devise.config
  get '/admin/reports/all_complete_apps', to: 'admin/reports#all_complete_apps', as: :admin_reports_all_complete_apps
  get '/admin/reports/registered_but_not_applied', to: 'admin/reports#registered_but_not_applied', as: :admin_reports_registered_but_not_applied
  get '/admin/reports/enrolled_with_addresses', to: 'admin/reports#enrolled_with_addresses', as: :admin_reports_enrolled_with_addresses
  get '/admin/reports/course_assignments_with_students', to: 'admin/reports#course_assignments_with_students', as: :admin_reports_course_assignments_with_students

  ActiveAdmin.routes(self)
  # authenticated :admin do
    resources :genders
    resources :demographics

    resources :camp_configurations do
      resources :camp_occurrences
    end

    resources :camp_occurrences do
      resources :activities
    end

    resources :camp_occurrences do
      resources :courses
    end

    resources :activities
    resources :courses
  # end

  devise_for :users
  resources :applicant_details

  resources :enrollments do
    resources :travels
  end

  resources :enrollments do
    resources :activities
  end

  resources :enrollments do
      resources :financial_aids
  end

  resources :financial_aids

  resources :enrollments do
    resources :recommendations
  end

  resources :recommendations

  resources :enrollments do
    resources :course_preferences
  end

  resources :enrollments do
    resources :course_assignments
  end

  resources :enrollments do
    resources :session_assignments
  end

  resources :course_preferences
  resources :course_assignments
  resources :session_assignments
  
  # post 'accept_offer', to: 'enrollments#accept_offer'
  # post 'decline_offer', to: 'enrollments#decline_offer'

  post 'accept_session_offer/:id', to: 'session_assignments#accept_session_offer', as: :accept_session_offer
  post 'decline_session_offer/:id', to: 'session_assignments#decline_session_offer', as: :decline_session_offer

  post 'waitlisted/:id', to: 'enrollments#add_to_waitlist', as: :waitlisted

  get 'static_pages/index'
  get 'static_pages/contact'
  get 'static_pages/privacy'


  get 'payments', to: 'payments#index'
  get 'payment_receipt', to: 'payments#payment_receipt'
  post 'payment_receipt', to: 'payments#payment_receipt'
  get 'payment_show', to: 'payments#payment_show', as: 'all_payments'
  get 'make_payment', to: 'payments#make_payment'
  post 'make_payment', to: 'payments#make_payment'

  get 'recupload_error', to: 'recuploads#error'
  get 'recupload_success', to: 'recuploads#success'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get 'send_request_email', to: 'recommendations#send_request_email', as: :send_request_email

end

app/models/enrollment.rb
# == Schema Information
#
# Table name: enrollments
#
#  id                          :bigint           not null, primary key
#  user_id                     :bigint           not null
#  international               :boolean          default(FALSE), not null
#  high_school_name            :string           not null
#  high_school_address1        :string           not null
#  high_school_address2        :string
#  high_school_city            :string           not null
#  high_school_state           :string
#  high_school_non_us          :string
#  high_school_postalcode      :string
#  high_school_country         :string           not null
#  year_in_school              :string           not null
#  anticipated_graduation_year :string           not null
#  room_mate_request           :string
#  personal_statement          :text             not null
#  notes                       :text
#  application_status          :string
#  offer_status                :string
#  partner_program             :string
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#  campyear                    :integer
#  application_deadline        :date
#
class Enrollment < ApplicationRecord
  after_update :send_offer_letter
  before_update :set_application_deadline
  after_commit :send_enroll_letter, if: :persisted?
  after_commit :send_rejected_letter, if: :persisted?
  after_commit :send_waitlisted_letter, if: :persisted?

  belongs_to :user
  has_one :applicant_detail, through: :user

  has_many :enrollment_activities, dependent: :destroy
  has_many :registration_activities, through: :enrollment_activities, source: :activity

  has_many :session_activities, dependent: :destroy 
  has_many :session_registrations, through: :session_activities, source: :camp_occurrence

  has_many :session_assignments, dependent: :destroy
  accepts_nested_attributes_for :session_assignments, allow_destroy: true

  has_many :course_preferences, dependent: :destroy
  has_many :course_registrations, through: :course_preferences, source: :course
  accepts_nested_attributes_for :course_preferences, allow_destroy: true

  has_many :course_assignments, dependent: :destroy
  accepts_nested_attributes_for :course_assignments, allow_destroy: true

  has_many :financial_aids, dependent: :destroy
  has_many :travels, dependent: :destroy
  has_one :recommendation, dependent: :destroy

  has_one :rejection, dependent: :destroy

  has_one_attached :transcript
  has_one_attached :student_packet

  validates :high_school_name, presence: true
  validates :high_school_address1, presence: true
  validates :high_school_city, presence: true
  validates :high_school_country, presence: true
  validates :year_in_school, presence: true
  validates :anticipated_graduation_year, presence: true
  validates :personal_statement, presence: true
  validates :personal_statement, length: { minimum: 100 }

  validate :at_least_one_session_is_checked
  validate :at_least_one_course_is_checked

  validate :validate_transcript_presence
  validate :acceptable_transcript

  validate :acceptable_student_packet

  scope :current_camp_year_applications, -> { where('campyear = ? ', CampConfiguration.active_camp_year) }
  scope :offered, -> { current_camp_year_applications.where("offer_status = 'offered'")}
  scope :accepted, -> { current_camp_year_applications.where("offer_status = 'accepted'")}
  scope :enrolled, -> { current_camp_year_applications.where("application_status = 'enrolled'")}
  scope :application_complete, -> {  current_camp_year_applications.where("application_status = 'application complete'")}
  scope :application_complete_not_offered, -> {  application_complete.where(offer_status: [nil, ""])}

  def display_name
    "#{self.applicant_detail.full_name} - #{self.user.email}"
  end

  def last_name
    "#{self.applicant_detail.lastname} - #{self.user.email}"
  end

  private

  def at_least_one_session_is_checked
    if session_registration_ids.empty?
      errors.add(:base, "Select at least one session")
    end
  end

  def at_least_one_course_is_checked
    if course_registration_ids.empty?
      errors.add(:base, "Select at least one course")
    end
  end

  def validate_transcript_presence
    errors.add(:transcript, 'should exist') unless self.transcript.attached?
  end

  def acceptable_transcript
    return unless transcript.attached?

    unless transcript.blob.byte_size <= 5.megabyte
      errors.add(:transcript, "is too big - file size cannot exceed 5Mbyte")
    end

    acceptable_types = ["image/png", "image/jpeg", "application/pdf"]
    unless acceptable_types.include?(transcript.content_type)
      errors.add(:transcript, "must be file type PDF, JPEG or PNG")
    end
  end

  def acceptable_student_packet
    return unless student_packet.attached?

    unless student_packet.blob.byte_size <= 5.megabyte
      errors.add(:student_packet, "is too big - file size cannot exceed 5Mbyte")
    end

    acceptable_types = ["image/png", "image/jpeg", "application/pdf"]
    unless acceptable_types.include?(student_packet.content_type)
      errors.add(:student_packet, "must be file type PDF, JPEG or PNG")
    end
  end

  def send_offer_letter
    if previous_changes[:offer_status]
      if self.offer_status == "offered"
        OfferMailer.offer_email(self.user_id).deliver_now
      end
    end
  end

  def send_enroll_letter
    if previous_changes[:application_status]
      if self.application_status == "enrolled"
        RegistrationMailer.app_enrolled_email(self.user).deliver_now
      end
    end
  end

  def send_rejected_letter
    if previous_changes[:application_status]
      if self.application_status == "rejected"
        RejectedMailer.app_rejected_email(self).deliver_now
      end
    end
  end

  def send_waitlisted_letter
    if previous_changes[:application_status]
      if self.application_status == "waitlisted"
        WaitlistedMailer.app_waitlisted_email(self).deliver_now
      end
    end
  end

  def set_application_deadline
    if self.session_assignments.present? && self.course_assignments.present?
      self.application_deadline = 30.days.from_now unless self.application_deadline.present?
    end
  end

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  include ApplicantState

  devise_group :logged_in, contains: [:user, :admin]
  before_action :authenticate_logged_in!
  before_action :authenticate_admin!, only: [:index, :destroy]

  before_action :set_current_enrollment, only: [:show, :edit, :update, :destroy]
  before_action :set_course_sessions
  before_action :set_activities_sessions

  # GET /enrollments
  # GET /enrollments.json
  def index
    if admin_signed_in?
      @enrollments = Enrollment.all
    else
      redirect_to root_path
    end
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
    @registration_activities = @current_enrollment.registration_activities.order(camp_occurrence_id: :asc)
    @session_registrations = @current_enrollment.session_registrations.order(description: :asc)
    @course_registrations = @current_enrollment.course_registrations.order(camp_occurrence_id: :asc)
    @room_mate = get_room_mate
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = current_user.enrollments.create(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to root_path, notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    respond_to do |format|
      if @current_enrollment.update(enrollment_params)
        if @current_enrollment.student_packet.attached? && balance_due == 0
          @current_enrollment.update!(application_status: "enrolled")
        end
        format.html { redirect_to root_path, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @current_enrollment }
      else
        if @current_enrollment.errors.include?(:student_packet)
          format.html { redirect_to root_path, alert: @current_enrollment.errors.full_messages.to_sentence }
        else
          format.html { render :edit }
          format.json { render json: @current_enrollment.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_to_waitlist
    @enrollment = Enrollment.find(params[:id])
    @enrollment.update(application_status: 'waitlisted')
    respond_to do |format|
      format.html { redirect_to admin_applications_path, notice: 'Application was placed on waitlist.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_current_enrollment
      @current_enrollment = current_user.enrollments.current_camp_year_applications.last
    end

    def set_course_sessions
      CampOccurrence.active.each do |ca|
        if ca.description == "Session 1"
          @courses_session1 = ca.courses.is_open.order(title: :asc)
        end
        if ca.description == "Session 2"
          @courses_session2 = ca.courses.is_open.order(title: :asc)
        end 
        if ca.description == "Session 3"
          @courses_session3 = ca.courses.is_open.order(title: :asc)
        end
      end  
    end

    def set_activities_sessions
      CampOccurrence.active.each do |as|
        if as.description == "Session 1"
          @activities_session1 = as.activities.active.order(description: :asc)
        end
        if as.description == "Session 2"
          @activities_session2 = as.activities.active.order(description: :asc)
        end
        if as.description == "Session 3"
          @activities_session3 = as.activities.active.order(description: :asc)
        end
      end  
    end

    def get_room_mate
      unless @current_enrollment.room_mate_request.blank?
        "I want to room with #{@current_enrollment.room_mate_request}."
      else
        "No specific room mate requested"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_params
      params.require(:enrollment).permit(
                          :user_id, :international, :high_school_name,
                          :high_school_address1, :high_school_address2,
                          :high_school_city, :high_school_state,
                          :high_school_non_us, :high_school_postalcode,
                          :high_school_country, :year_in_school,
                          :anticipated_graduation_year, :room_mate_request,
                          :personal_statement, :shirt_size, :notes,
                          :application_status, :offer_status,
                          :partner_program, :transcript,
                          :student_packet, :campyear,
                          registration_activity_ids: [],
                          session_registration_ids: [],
                          course_registration_ids: [])
    end
end

app/views/enrollments/_course_preview.html.erb
<h4>The course that are available for the different sessions:</h4>
<p>
  Be sure to select a session(s) that offers the course(s) you are interested
  in.
</p>
<p>You will choose your Course Preferences after this step.</p>
<% if @courses_session1.present? %>
<h5>Session 1</h5>
<ul class="px-4">
  <% @courses_session1.each do |c| %>
    <li class="text-xs">
      <%= "#{ c.title } -- #{c.camp_occurrence.description}" %>
    </li>
  <% end %>
</ul>
<% end %>

<% if @courses_session2.present? %>
<h5>Session 2</h5>
<ul class="px-4">
  <% @courses_session2.each do |c| %>
    <li class="text-xs">
      <%= "#{ c.title } -- #{c.camp_occurrence.description}" %>
    </li>
  <% end %>
</ul>
<% end %>

<% if @courses_session3.present? %>
<h5>Session 3</h5>

<ul class="px-4">
  <% @courses_session3.each do |c| %>
    <li class="text-xs">
      <%= "#{ c.title } -- #{c.camp_occurrence.description}" %>
    </li>
  <% end %>
</ul>

<% end %>

app/views/enrollments/edit.html.erb
<div class="max-w rounded overflow-hidden shadow-lg">
  <h1 class="text-yellow-um_yellow bg-blue-um_blue p-2">Editing Application</h1>
  <div class="m-2">
    <%= render 'form', enrollment: @current_enrollment %>
  </div>
</div>

<div class="mt-2">
  <%= link_to 'Back', enrollment_path(@current_enrollment), class: "btn btn-blue" %>
</div>

app/views/enrollments/index.html.erb
<h1>Applications</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>International</th>
      <th>High school name</th>
      <th>High school address1</th>
      <th>High school address2</th>
      <th>High school city</th>
      <th>High school state</th>
      <th>High school non us</th>
      <th>High school postalcode</th>
      <th>High school country</th>
      <th>Year in school</th>
      <th>Anticipated graduation year</th>
      <th>Room mate request</th>
      <th>Personal statement</th>
      <th>Notes</th>
      <th>Application status</th>
      <th>Offer status</th>
      <th>Partner program</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= enrollment.user_id %></td>
        <td><%= enrollment.international %></td>
        <td><%= enrollment.high_school_name %></td>
        <td><%= enrollment.high_school_address1 %></td>
        <td><%= enrollment.high_school_address2 %></td>
        <td><%= enrollment.high_school_city %></td>
        <td><%= enrollment.high_school_state %></td>
        <td><%= enrollment.high_school_non_us %></td>
        <td><%= enrollment.high_school_postalcode %></td>
        <td><%= enrollment.high_school_country %></td>
        <td><%= enrollment.year_in_school %></td>
        <td><%= enrollment.anticipated_graduation_year %></td>
        <td><%= enrollment.room_mate_request %></td>
        <td><%= enrollment.personal_statement %></td>
        <% if admin_signed_in? %>
          <td><%= enrollment.notes %></td>
          <td><%= enrollment.application_status %></td>
          <td><%= enrollment.offer_status %></td>
          <td><%= enrollment.partner_program %></td>
        <% end %>
        <td><%= link_to 'Show', enrollment %></td>
        <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
        <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enrollment', new_enrollment_path %>

app/views/enrollments/new.html.erb
<div class="max-w rounded overflow-hidden shadow-lg">
  <h1 class="text-yellow-um_yellow bg-blue-um_blue p-2">New Application</h1>
  <div class="m-2">
    <%= render 'form', enrollment: @enrollment %>
  </div>
</div>

<div class="mt-2">
  <%= link_to 'Back', root_path, class: "btn btn-blue" %>
</div>

app/views/enrollments/show.html.erb
<div class="max-w rounded overflow-hidden shadow-lg mb-2">
  <h1 class="text-yellow-um_yellow bg-blue-um_blue p-2">
    <p class="text-center text-lg"><%= @current_enrollment.applicant_detail.full_name %>'s <%= @current_enrollment.campyear %> Application</p>
  </h1>
  <div class="px-6 py-2">
    <div class="bg-gray-200 rounded-lg px-3 py-1 text-base text-gray-700 mr-2 mb-2">
      <ul>
        <li>Grade level: <%= @current_enrollment.year_in_school %></li>
        <li>Expected graduation: <%= @current_enrollment.anticipated_graduation_year %></li>
      </ul>
    </div>
    <div class="bg-gray-200 rounded-lg px-3 py-1 text-base text-gray-700 mr-2 mb-2">
      <p class="text-gray-700">
        High school information:
          <ul class="pl-4">
            <li><%= @current_enrollment.high_school_name %></li>
            <li><%= @current_enrollment.high_school_address1 %></li>
            <li><%= @current_enrollment.high_school_address2 %></li>
            <li>
              <%= @current_enrollment.high_school_city %>, 
              <%= @current_enrollment.high_school_state %>
              <%= @current_enrollment.high_school_non_us %>
              <%= @current_enrollment.high_school_postalcode %>
            </li>
            <li><%= @current_enrollment.high_school_country %></li>
          </ul>
      </p>
    </div>
    <div class="bg-gray-200 rounded-lg px-3 text-gray-700 mr-2">
      <%= @room_mate %>
    </div>
  </div>

<p class="current-uploaded-docs h-40 overflow-auto">
  <strong>Personal statement:</strong>
  <%= @current_enrollment.personal_statement %>
</p>

<% if @current_enrollment.transcript.attached? %>
  <p class="current-uploaded-docs">
    <strong>Transcript:</strong> <%= link_to @current_enrollment.transcript.filename, url_for(@current_enrollment.transcript) %>
  </p>
<% else %>
  <p class="text-lg text-orange-500">
    Use the <%= link_to 'Edit', edit_enrollment_path(@current_enrollment) %> button to add a transcript!
  </p>
<% end %>

<% if @session_registrations.present? %>
  <div class="display-box mt-2">
  <div class="section-header">Sessions</div>
    <ul>
      <% @session_registrations.each do |s| %>
        <li>
          <%= s.description_with_date %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>


<% if @registration_activities.present? %>
  <div class="display-box mt-2">
  <div class="section-header">Activities & Services</div>
    <ul>
      <% @registration_activities.each do |r| %>
        <li>
          <%= r.description %> -- <%= humanized_money_with_symbol(r.cost) %> <%= r.camp_occurrence.description %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>



<% if @course_registrations.present? %>
  <div class="display-box mt-2">
  <div class="section-header">Course Selections</div>
    <ul>
      <% @course_registrations.each do |c| %>
        <li>
          <%= c.title %> [ <%= @current_enrollment.course_preferences.find_by(course_id: c.id).ranking %> ] -- <%= c.camp_occurrence.description %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>


<% if admin_signed_in? %>
  <h2>========== Administrative area ==========</h2>
  <p>
    <small>User_id:
    <%= @current_enrollment.user_id %>
    </small>
  </p>
  <p>
    <strong>Notes:</strong>
    <%= @current_enrollment.notes %>
  </p>
  <p>
    <strong>Application status:</strong>
    <%= @current_enrollment.application_status %>
  </p>

  <p>
    <strong>Offer status:</strong>
    <%= @current_enrollment.offer_status %>
  </p>

  <p>
    <strong>Partner program:</strong>
    <%= @current_enrollment.partner_program %>
  </p>
<% end %>
</div>
<div class="mt-2">
  <% if @current_enrollment.application_status == "" || @current_enrollment.application_status == nil %>
    <%= link_to 'Edit', edit_enrollment_path(@current_enrollment), class: "btn btn-blue" %> |
  <% end %>
  <%= link_to 'Home', root_path, class: "btn btn-blue" %>
</div>