config/routes.rb
Rails.application.routes.draw do


  resources :rejections
  resources :campnotes
  resources :recuploads
  resources :feedbacks
  # resources :payments
  root to: 'static_pages#index'

  devise_for :admins, ActiveAdmin::Devise.config
  get '/admin/reports/all_complete_apps', to: 'admin/reports#all_complete_apps', as: :admin_reports_all_complete_apps
  get '/admin/reports/registered_but_not_applied', to: 'admin/reports#registered_but_not_applied', as: :admin_reports_registered_but_not_applied
  get '/admin/reports/enrolled_with_addresses', to: 'admin/reports#enrolled_with_addresses', as: :admin_reports_enrolled_with_addresses
  get '/admin/reports/course_assignments_with_students', to: 'admin/reports#course_assignments_with_students', as: :admin_reports_course_assignments_with_students

  ActiveAdmin.routes(self)
  # authenticated :admin do
    resources :genders
    resources :demographics

    resources :camp_configurations do
      resources :camp_occurrences
    end

    resources :camp_occurrences do
      resources :activities
    end

    resources :camp_occurrences do
      resources :courses
    end

    resources :activities
    resources :courses
  # end

  devise_for :users
  resources :applicant_details

  resources :enrollments do
    resources :travels
  end

  resources :enrollments do
    resources :activities
  end

  resources :enrollments do
      resources :financial_aids
  end

  resources :financial_aids

  resources :enrollments do
    resources :recommendations
  end

  resources :recommendations

  resources :enrollments do
    resources :course_preferences
  end

  resources :enrollments do
    resources :course_assignments
  end

  resources :enrollments do
    resources :session_assignments
  end

  resources :course_preferences
  resources :course_assignments
  resources :session_assignments
  
  # post 'accept_offer', to: 'enrollments#accept_offer'
  # post 'decline_offer', to: 'enrollments#decline_offer'

  post 'accept_session_offer/:id', to: 'session_assignments#accept_session_offer', as: :accept_session_offer
  post 'decline_session_offer/:id', to: 'session_assignments#decline_session_offer', as: :decline_session_offer

  post 'waitlisted/:id', to: 'enrollments#add_to_waitlist', as: :waitlisted

  get 'static_pages/index'
  get 'static_pages/contact'
  get 'static_pages/privacy'


  get 'payments', to: 'payments#index'
  get 'payment_receipt', to: 'payments#payment_receipt'
  post 'payment_receipt', to: 'payments#payment_receipt'
  get 'payment_show', to: 'payments#payment_show', as: 'all_payments'
  get 'make_payment', to: 'payments#make_payment'
  post 'make_payment', to: 'payments#make_payment'

  get 'recupload_error', to: 'recuploads#error'
  get 'recupload_success', to: 'recuploads#success'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get 'send_request_email', to: 'recommendations#send_request_email', as: :send_request_email

end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id                 :bigint           not null, primary key
#  camp_occurrence_id :bigint           not null
#  description        :string           not null
#  cost_cents         :integer          not null
#  date_occurs        :date             not null
#  active             :boolean          default(FALSE), not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
class Activity < ApplicationRecord
  include MoneyRails::ActionViewExtension
  belongs_to :camp_occurrence
  has_many :enrollment_activities
  has_many :enrolled_users, through: :enrollment_activities, source: :enrollment

  monetize :cost_cents

  validates :description, presence: true
  validates :date_occurs, presence: true, format: { with: ConstantData::VALID_DATE_REGEX }
  validates :cost_cents, presence: true, numericality: { only_integer: true }

  def description_with_cost
    "#{description} -- #{humanized_money_with_symbol(self.cost)}"
  end

  scope :active, -> { where(active: true).order(description: :asc) }
  
  def display_name
    "#{self.description} - #{self.camp_occurrence.description}" # or whatever column you want
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_admin!, only: [:index, :show, :edit, :update, :destroy]
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all.order( :camp_occurrence_id, :date_occurs )
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end


  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @camp_occurrence = CampOccurrence.find(params[:camp_occurrence_id])
    @camp_configuration = @camp_occurrence.camp_configuration_id
    @activity = @camp_occurrence.activities.create(activity_params)
    if @activity.errors 
      render :edit
    else 
      redirect_to activities_path, notice: 'Activity was successfully created.'
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    def set_camp_occurrence
      @camp_occurrence = CampOccurrence.find(params[:camp_occurrence_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:camp_occurrence_id, :description, :cost_cents, :date_occurs, :active)
    end
end

app/views/activities/_activity.html.erb
<p><%= activity.id %> | <%= link_to activity.description, camp_occurrence_activity_path(@camp_occurrence, activity) %>

<p> Edit this Activity:</p>

<%= render 'activities/form', activity: activity %>

<p><%= link_to 'Delete activity', camp_occurrence_activity_path(@camp_occurrence, activity), method: :delete %></p>

<p>======================</p>
<br>

app/views/activities/_form.html.erb
<%= form_with(model: [ @camp_occurrence, activity ], local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :camp_occurrence_id %>
    <%= form.text_field :camp_occurrence_id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :cost_cents %>
    <%= form.text_field :cost_cents %>
  </div>

  <div class="field">
    <%= form.label :date_occurs %>
    <%= form.date_select :date_occurs %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Activities</h1>

<table>
  <thead>
    <tr>
      <th>Camp<br>Occurrence</th>
      <th>Description</th>
      <th>Cost</th>
      <th>Date occurs</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= link_to "#{activity.camp_occurrence.description.titleize} - #{activity.camp_occurrence.camp_configuration.camp_year}", camp_configuration_camp_occurrence_path(activity.camp_occurrence.camp_configuration_id, activity.camp_occurrence) %></td>
        <td><%= activity.description %></td>
        <td><%= humanized_money_with_symbol(activity.cost) %></td>
        <td><%= activity.date_occurs %></td>
        <td><%= activity.active %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Camp Configurations', camp_configurations_path %>

app/views/activities/show.html.erb
<p>
  <strong>Camp Occurrence:</strong>
  <%= @activity.camp_occurrence_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @activity.description %>
</p>

<p>
  <strong>Cost in cents:</strong>
  <%= @activity.cost %>
</p>

<p>
  <strong>Date occurs:</strong>
  <%= @activity.date_occurs %>
</p>

<p>
  <strong>Active:</strong>
  <%= @activity.active %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>