config/routes.rb
Rails.application.routes.draw do


  resources :rejections
  resources :campnotes
  resources :recuploads
  resources :feedbacks
  # resources :payments
  root to: 'static_pages#index'

  devise_for :admins, ActiveAdmin::Devise.config
  get '/admin/reports/all_complete_apps', to: 'admin/reports#all_complete_apps', as: :admin_reports_all_complete_apps
  get '/admin/reports/registered_but_not_applied', to: 'admin/reports#registered_but_not_applied', as: :admin_reports_registered_but_not_applied
  get '/admin/reports/enrolled_with_addresses', to: 'admin/reports#enrolled_with_addresses', as: :admin_reports_enrolled_with_addresses
  get '/admin/reports/course_assignments_with_students', to: 'admin/reports#course_assignments_with_students', as: :admin_reports_course_assignments_with_students

  ActiveAdmin.routes(self)
  # authenticated :admin do
    resources :genders
    resources :demographics

    resources :camp_configurations do
      resources :camp_occurrences
    end

    resources :camp_occurrences do
      resources :activities
    end

    resources :camp_occurrences do
      resources :courses
    end

    resources :activities
    resources :courses
  # end

  devise_for :users
  resources :applicant_details

  resources :enrollments do
    resources :travels
  end

  resources :enrollments do
    resources :activities
  end

  resources :enrollments do
      resources :financial_aids
  end

  resources :financial_aids

  resources :enrollments do
    resources :recommendations
  end

  resources :recommendations

  resources :enrollments do
    resources :course_preferences
  end

  resources :enrollments do
    resources :course_assignments
  end

  resources :enrollments do
    resources :session_assignments
  end

  resources :course_preferences
  resources :course_assignments
  resources :session_assignments
  
  # post 'accept_offer', to: 'enrollments#accept_offer'
  # post 'decline_offer', to: 'enrollments#decline_offer'

  post 'accept_session_offer/:id', to: 'session_assignments#accept_session_offer', as: :accept_session_offer
  post 'decline_session_offer/:id', to: 'session_assignments#decline_session_offer', as: :decline_session_offer

  post 'waitlisted/:id', to: 'enrollments#add_to_waitlist', as: :waitlisted

  get 'static_pages/index'
  get 'static_pages/contact'
  get 'static_pages/privacy'


  get 'payments', to: 'payments#index'
  get 'payment_receipt', to: 'payments#payment_receipt'
  post 'payment_receipt', to: 'payments#payment_receipt'
  get 'payment_show', to: 'payments#payment_show', as: 'all_payments'
  get 'make_payment', to: 'payments#make_payment'
  post 'make_payment', to: 'payments#make_payment'

  get 'recupload_error', to: 'recuploads#error'
  get 'recupload_success', to: 'recuploads#success'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get 'send_request_email', to: 'recommendations#send_request_email', as: :send_request_email

end

app/models/campnote.rb
# == Schema Information
#
# Table name: campnotes
#
#  id         :bigint           not null, primary key
#  note       :string
#  opendate   :datetime
#  closedate  :datetime
#  notetype   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Campnote < ApplicationRecord
  validates :note, :notetype, presence: true

  validates :opendate, :closedate, presence: true, availability: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if closedate.blank? || opendate.blank?

    if closedate < opendate
      errors.add(:closedate, "must be after the start date")
    end
 end

end

app/controllers/campnotes_controller.rb
class CampnotesController < ApplicationController
  before_action :set_campnote, only: [:show, :edit, :update, :destroy]

  # GET /campnotes
  # GET /campnotes.json
  def index
    @campnotes = Campnote.all
  end

  # GET /campnotes/1
  # GET /campnotes/1.json
  def show
  end

  # GET /campnotes/new
  def new
    @campnote = Campnote.new
  end

  # GET /campnotes/1/edit
  def edit
  end

  # POST /campnotes
  # POST /campnotes.json
  def create
    @campnote = Campnote.new(campnote_params)

    respond_to do |format|
      if @campnote.save
        format.html { redirect_to @campnote, notice: 'Campnote was successfully created.' }
        format.json { render :show, status: :created, location: @campnote }
      else
        format.html { render :new }
        format.json { render json: @campnote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campnotes/1
  # PATCH/PUT /campnotes/1.json
  def update
    respond_to do |format|
      if @campnote.update(campnote_params)
        format.html { redirect_to @campnote, notice: 'Campnote was successfully updated.' }
        format.json { render :show, status: :ok, location: @campnote }
      else
        format.html { render :edit }
        format.json { render json: @campnote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campnotes/1
  # DELETE /campnotes/1.json
  def destroy
    @campnote.destroy
    respond_to do |format|
      format.html { redirect_to campnotes_url, notice: 'Campnote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campnote
      @campnote = Campnote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def campnote_params
      params.require(:campnote).permit(:note, :opendate, :closedate, :notetype)
    end
end

app/views/campnotes/_form.html.erb
<%= semantic_form_for @campnote do |f| %>
  <%= f.inputs do %>
    <%= f.input :note %>
    <%= f.input :opendate %>
    <%= f.input :closedate %>
    <%= f.input :notetype %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/campnotes/edit.html.erb
<h1>Editing Campnote</h1>

<%= render 'form', campnote: @campnote %>

<%= link_to 'Show', @campnote %> |
<%= link_to 'Back', campnotes_path %>

app/views/campnotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campnotes</h1>

<table>
  <thead>
    <tr>
      <th>Note</th>
      <th>Opendate</th>
      <th>Closedate</th>
      <th>Notetype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campnotes.each do |campnote| %>
      <tr>
        <td><%= campnote.note %></td>
        <td><%= campnote.opendate %></td>
        <td><%= campnote.closedate %></td>
        <td><%= campnote.notetype %></td>
        <td><%= link_to 'Show', campnote %></td>
        <td><%= link_to 'Edit', edit_campnote_path(campnote) %></td>
        <td><%= link_to 'Destroy', campnote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campnote', new_campnote_path %>

app/views/campnotes/new.html.erb
<h1>New Campnote</h1>

<%= render 'form', campnote: @campnote %>

<%= link_to 'Back', campnotes_path %>

app/views/campnotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Note:</strong>
  <%= @campnote.note %>
</p>

<p>
  <strong>Opendate:</strong>
  <%= @campnote.opendate %>
</p>

<p>
  <strong>Closedate:</strong>
  <%= @campnote.closedate %>
</p>

<p>
  <strong>Notetype:</strong>
  <%= @campnote.notetype %>
</p>

<%= link_to 'Edit', edit_campnote_path(@campnote) %> |
<%= link_to 'Back', campnotes_path %>